Repository build-trust/ockam, pull requests merged in 2022-11, with the labels that each got.

#3783 feat(rust): always load policy from storage
  implementations/rust/ockam/ockam_abac/src/policy.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
Labels: auto-merge

#3770 feat(elixir): allow configuring idle timeout for workers
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/identity/identity_channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/worker.ex
Labels: auto-merge

#3789 feat(rust): make the okta tenant config more generic
  implementations/rust/ockam/ockam_api/src/cloud/project.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/services.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/services.rs
  implementations/rust/ockam/ockam_api/src/okta/mod.rs
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
  implementations/rust/ockam/ockam_command/src/service/config.rs
  implementations/rust/ockam/ockam_command/src/service/start.rs
Labels: auto-merge

#3791 feat(rust): add default value for `to` argument and change the `attributes` argument name
  implementations/rust/ockam/ockam_command/src/project/enroll.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3793 feat(rust): `check-credential` argument defaults to node's `enable-credential-checks` value
  implementations/rust/ockam/ockam_api/src/nodes/models/portal.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3796 chore(rust): rename attr argument to attribute on okta addon config
  implementations/rust/ockam/ockam_command/src/project/addon.rs
Labels: auto-merge

#3795 fix(rust): increase timeout used on the `is_node_up` requests
  implementations/rust/ockam/ockam_command/src/node/show.rs
Labels: auto-merge

#3781 refactor(rust): avoid using non-borrowing cbor fields
  implementations/rust/ockam/ockam_api/src/cloud/project.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/base.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/portal.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/services.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs
  implementations/rust/ockam/ockam_command/src/node/show.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_core/src/cbor_utils/cow_str.rs
Labels: auto-merge

#3785 feat(rust): wrap stored policy expressions
  implementations/rust/ockam/ockam_api/src/lmdb.rs
Labels: auto-merge

#3776 refactor(rust): Extract multi addr processing
  implementations/rust/ockam/ockam_command/src/forwarder/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
Labels: auto-merge, hacktoberfest-accepted

#3809 fix(elixir): fail if unable to verify identity on credential api setup
  implementations/elixir/ockam/ockam_services/lib/services/api/credential_exchange_api.ex
  implementations/elixir/ockam/ockam_typed_cbor/lib/typed_cbor.ex
Labels: auto-merge

#3813 refactor(elixir): split secure channel files
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/data.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/handshake.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/handshake_message/identity_channel_message.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/handshake_message/request.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/handshake_message/response.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/secure_channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/identity/identity_channel.ex
Labels: auto-merge

#3810 feat(rust): waits until project is ready after okta plugin is enabled
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
Labels: auto-merge

#3814 fix(rust): improve output when waiting for project to be ready
  implementations/rust/ockam/ockam_command/src/project/util.rs
Labels: auto-merge

#3778 refactor(elixir): session handshake and worker option names
  implementations/elixir/ockam/ockam/lib/ockam/examples/session/count_to.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/session/pipe_channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/session/routing.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/secure_channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/pipe_channel/initiator.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/pipe_channel/responder.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/pluggable.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/pluggable/initiator.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/pluggable/responder.ex
  implementations/elixir/ockam/ockam/test/ockam/session/session_test.exs
Labels: auto-merge, hacktoberfest-accepted

#3825 read release shasum file content as an array
  tools/scripts/release/release.sh
Labels: auto-merge

#3817 fix(rust): change if/and/or evaluation of abac expressions
  implementations/rust/ockam/ockam_abac/src/eval.rs
Labels: auto-merge

#3826 feat(rust): adapt and re enable complex bats tests
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3812 chore(rust): add comment about always starting echoer service
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
Labels: auto-merge

#3815 fix(rust): unused manifest key warning
  Cargo.toml
  implementations/rust/ockam/ockam_command/Cargo.toml
Labels: auto-merge

#3828 refactor(rust): 'tcp connection delete' command to use 'rpc' abstraction
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3830 ci: add draft-binaries workflow
  .github/workflows/draft-binaries.yml
Labels: auto-merge

#3834 ci(rust): cache build output in "ockam command test" workflow
  .github/workflows/ockam_command.yml
Labels: auto-merge

#3838 fix(rust): disable address debugging by default
  implementations/rust/ockam/ockam_node/Cargo.toml
Labels: auto-merge

#3833 chore(rust): address clippy messages
  implementations/rust/ockam/ockam_api/src/lib.rs
  implementations/rust/ockam/ockam_api/src/session/sessions.rs
  implementations/rust/ockam/ockam_command/build.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/space/mod.rs
  implementations/rust/ockam/ockam_core/src/api.rs
  implementations/rust/ockam/ockam_identity/src/identifiers.rs
  implementations/rust/ockam/ockam_macros/src/async_try_clone_derive.rs
  implementations/rust/ockam/ockam_macros/src/internals/check.rs
Labels: auto-merge

#3848 chore(rust): identity show do not run on embedded node
  implementations/rust/ockam/ockam_command/src/identity/show.rs
Labels: auto-merge

#3844 refactor(rust): force shared identity on CLI
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/start.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/util/startup.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3851 fix(rust): environment variables on bats tests
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3856 docs: key agreement protocol
  documentation/architecture/key_agreement/README.md
  documentation/architecture/key_agreement/diagrams/xx.svg
Labels: auto-merge

#3842 feat(rust): define a new structure to store CLI state and config
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/state.rs
  implementations/rust/ockam/ockam_identity/src/identity.rs
Labels: auto-merge

#3853 refactor(rust): use new state structure on `vault create` command
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/state.rs
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3854 refactor(rust): use new state structure on `identity create` command
  implementations/rust/ockam/ockam_command/src/identity/create.rs
  implementations/rust/ockam/ockam_command/src/state.rs
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/tests/cmd_enroll.rs
  implementations/rust/ockam/ockam_command/tests/cmd_project.rs
  implementations/rust/ockam/ockam_command/tests/cmd_space.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3858 refactor(rust): move default vault/identity to defaults directory and other changes
  implementations/rust/ockam/ockam_command/src/state.rs
Labels: auto-merge

#3777 refactor(elixir): `TypedCBOR.encode()` returns a tuple on success and…
  implementations/elixir/ockam/ockam/lib/ockam/api/client.ex
  implementations/elixir/ockam/ockam/lib/ockam/api/client/discovery_client.ex
  implementations/elixir/ockam/ockam/lib/ockam/api/discovery/service_info.ex
  implementations/elixir/ockam/ockam/lib/ockam/api/request.ex
  implementations/elixir/ockam/ockam/lib/ockam/api/response.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/api/request.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/api/response.ex
  implementations/elixir/ockam/ockam/test/ockam/api/request_test.exs
  implementations/elixir/ockam/ockam/test/ockam/api/response_test.exs
  implementations/elixir/ockam/ockam_services/lib/services/api/discovery_api.ex
  implementations/elixir/ockam/ockam_typed_cbor/lib/typed_cbor.ex
  implementations/elixir/ockam/ockam_typed_cbor/test/plugin_test.exs
Labels: auto-merge, hacktoberfest-accepted

#3852 chore(rust): ockam command add subcommand to generate man pages
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/manpages.rs
Labels: auto-merge

#3860 refactor(rust): `identity create` creates default vault if doesn't exist
  implementations/rust/ockam/ockam_command/src/identity/create.rs
  implementations/rust/ockam/ockam_command/src/state.rs
  implementations/rust/ockam/ockam_command/src/vault/create.rs
Labels: auto-merge

#3700 Ockam node healthcheck application.
  .github/dependabot.yml
  .github/mergify.yml
  .github/workflows/elixir.yml
  implementations/elixir/build.gradle
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/handshake.ex
  implementations/elixir/ockam/ockam/lib/ockam/identity/secure_channel/secure_channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/initiator.ex
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/responder.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/pluggable/initiator.ex
  implementations/elixir/ockam/ockam/lib/ockam/telemetry_logger.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/tcp.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/client.ex
  implementations/elixir/ockam/ockam/lib/ockam/worker.ex
  implementations/elixir/ockam/ockam_healthcheck/.credo.exs
  implementations/elixir/ockam/ockam_healthcheck/.formatter.exs
  implementations/elixir/ockam/ockam_healthcheck/.gitignore
  implementations/elixir/ockam/ockam_healthcheck/config/config.exs
  implementations/elixir/ockam/ockam_healthcheck/config/dev.exs
  implementations/elixir/ockam/ockam_healthcheck/config/prod.exs
  implementations/elixir/ockam/ockam_healthcheck/config/runtime.exs
  implementations/elixir/ockam/ockam_healthcheck/config/test.exs
  implementations/elixir/ockam/ockam_healthcheck/lib/application.ex
  implementations/elixir/ockam/ockam_healthcheck/lib/healthcheck/healthcheck.ex
  implementations/elixir/ockam/ockam_healthcheck/lib/healthcheck/metrics.ex
  implementations/elixir/ockam/ockam_healthcheck/mix.exs
  implementations/elixir/ockam/ockam_healthcheck/mix.lock
  implementations/elixir/ockam/ockam_healthcheck/test/healthcheck/healthcheck_test.exs
  implementations/elixir/ockam/ockam_healthcheck/test/test_helper.exs
  implementations/elixir/ockam/ockam_metrics/lib/application.ex
  implementations/elixir/ockam/ockam_metrics/lib/telemetry_poller.ex
  implementations/elixir/ockam/ockam_services/lib/services/metrics/telemetry_poller.ex
  tools/docker/healthcheck/Dockerfile
Labels: Implementation: Elixir, auto-merge

#3868 fix(rust): `node delete` to affect only the `nodes` directory
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/reset.rs
Labels: auto-merge

#3869 refactor(rust): remove old configs and move missing fields to new node directory
  Cargo.lock
  implementations/rust/ockam/ockam_api/Cargo.toml
  implementations/rust/ockam/ockam_api/src/cli_state.rs
  implementations/rust/ockam/ockam_api/src/config/cli.rs
  implementations/rust/ockam/ockam_api/src/config/lookup.rs
  implementations/rust/ockam/ockam_api/src/nodes/config.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs
  implementations/rust/ockam/ockam_api/src/util.rs
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/admin/subscription.rs
  implementations/rust/ockam/ockam_command/src/configuration/get.rs
  implementations/rust/ockam/ockam_command/src/configuration/mod.rs
  implementations/rust/ockam/ockam_command/src/configuration/set.rs
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/error.rs
  implementations/rust/ockam/ockam_command/src/forwarder/create.rs
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/message/send.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/delete.rs
  implementations/rust/ockam/ockam_command/src/node/list.rs
  implementations/rust/ockam/ockam_command/src/node/mod.rs
  implementations/rust/ockam/ockam_command/src/node/run.rs
  implementations/rust/ockam/ockam_command/src/node/show.rs
  implementations/rust/ockam/ockam_command/src/node/start.rs
  implementations/rust/ockam/ockam_command/src/node/stop.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/project/add_enroller.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/project/auth.rs
  implementations/rust/ockam/ockam_command/src/project/create.rs
  implementations/rust/ockam/ockam_command/src/project/delete.rs
  implementations/rust/ockam/ockam_command/src/project/delete_enroller.rs
  implementations/rust/ockam/ockam_command/src/project/enroll.rs
  implementations/rust/ockam/ockam_command/src/project/info.rs
  implementations/rust/ockam/ockam_command/src/project/list.rs
  implementations/rust/ockam/ockam_command/src/project/list_enrollers.rs
  implementations/rust/ockam/ockam_command/src/project/show.rs
  implementations/rust/ockam/ockam_command/src/reset.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/create.rs
  implementations/rust/ockam/ockam_command/src/space/create.rs
  implementations/rust/ockam/ockam_command/src/space/delete.rs
  implementations/rust/ockam/ockam_command/src/space/list.rs
  implementations/rust/ockam/ockam_command/src/space/show.rs
  implementations/rust/ockam/ockam_command/src/subscription.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/util/config.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
  implementations/rust/ockam/ockam_command/src/util/startup.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3824 docs: add api reference docs
  documentation/reference/API.md
  documentation/reference/api/credential_exchange.md
  documentation/reference/api/discovery.md
  documentation/reference/api/orchestrator/auth0.md
  documentation/reference/api/orchestrator/project/addons.md
  documentation/reference/api/orchestrator/project/enrollers.md
  documentation/reference/api/orchestrator/projects.md
  documentation/reference/api/orchestrator/spaces.md
  documentation/reference/api/policies.md
  implementations/elixir/ockam/ockam/lib/ockam/api/discovery/service_info.ex
  implementations/elixir/ockam/ockam_services/lib/services/api.ex
  implementations/elixir/ockam/ockam_services/lib/services/api/discovery_api.ex
  implementations/elixir/ockam/ockam_services/lib/services/discovery/storage.ex
  implementations/elixir/ockam/ockam_services/lib/services/discovery/storage/supervisor.ex
Labels: auto-merge
