Repository build-trust/ockam, pull requests merged in 2022-10, with the labels that each got.

#3547 docs: update readme
  README.md
Labels: auto-merge

#3549 docs: improve readme
  README.md
Labels: auto-merge

#3550 docs: improve readme
  README.md
Labels: auto-merge

#3573 build(rust): upgrade to clap v4 release version
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/forwarder/create.rs
  implementations/rust/ockam/ockam_command/src/help.rs
  implementations/rust/ockam/ockam_command/src/lib.rs
Labels: auto-merge

#3570 feat(rust): updated deny.toml file path
  implementations/rust/build.gradle
  tools/cargo-deny/deny.toml
Labels: auto-merge

#3585 prepare 3571
  implementations/rust/ockam/ockam_command/src/identity/create.rs
  implementations/rust/ockam/ockam_command/src/identity/show.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs
  implementations/rust/ockam/ockam_command/src/service/start.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
  implementations/rust/ockam/ockam_command/src/util/config.rs
  implementations/rust/ockam/ockam_command/src/vault/create.rs
Labels: auto-merge

#3589 Prepare 3584
  implementations/rust/ockam/ockam_command/src/node/delete.rs
Labels: auto-merge

#3565 refactor(rust): `ockam_command::service::start` to use rpc
  implementations/rust/ockam/ockam_api/src/nodes/service/services.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/service/mod.rs
  implementations/rust/ockam/ockam_command/src/service/start.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3574 chore(Rust): Implement changes outlined in #3560
  implementations/rust/ockam/ockam_command/src/configuration/set_default_node.rs
Labels: auto-merge, hacktoberfest-accepted

#3592 refactor(rust): refactor identity create command to use rpc abstraction
  implementations/rust/ockam/ockam_command/src/identity/create.rs
  implementations/rust/ockam/ockam_command/src/identity/mod.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
Labels: auto-merge, hacktoberfest-accepted

#3519 feat(rust): extend the declarative config support
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/mod.rs
  implementations/rust/ockam/ockam_command/src/node/run.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/create.rs
Labels: auto-merge

#3590 refactor(rust): change `vault create` command to use `rpc` abstraction
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/src/vault/mod.rs
Labels: auto-merge, hacktoberfest-accepted

#3602 Allow unicode-ident license in deny.toml
  Cargo.lock
  tools/cargo-deny/deny.toml
Labels: auto-merge

#3606 build: add "coverage" profile to cargo
  Cargo.toml
  implementations/rust/DEVELOP.md
Labels: auto-merge

#3603 refactor(rust): change `configuration get` to delegate error mapping
  implementations/rust/ockam/ockam_command/src/configuration/get.rs
Labels: auto-merge, hacktoberfest-accepted

#3604 fix(rust): get default node stop manual error handling
  implementations/rust/ockam/ockam_command/src/configuration/get_default_node.rs
Labels: auto-merge, hacktoberfest-accepted

#3551 refactor(rust): `NodeManager` constructor
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
Labels: auto-merge, hacktoberfest-accepted, hacktoberfest

#3614 chore: typo and grammer fix for node command help
  implementations/rust/ockam/ockam_command/src/node/mod.rs
Labels: auto-merge, hacktoberfest-accepted

#3615 fix(rust): message send deletes --from node config
  implementations/rust/ockam/ockam_command/src/message/send.rs
Labels: auto-merge

#3623 ci: add github workflow to lint files using semgrep (#3617)
  .github/workflows/semgrep.yml
  tools/semgrep/.semgrepignore
  tools/semgrep/rules/example.yaml
Labels: auto-merge, hacktoberfest-accepted

#3608 refactor(rust): move `get_final_element` to `extract_node_name`
  implementations/rust/ockam/ockam_command/src/configuration/set_default_node.rs
  implementations/rust/ockam/ockam_command/src/forwarder/create.rs
  implementations/rust/ockam/ockam_command/src/identity/show.rs
  implementations/rust/ockam/ockam_command/src/message/send.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/create.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/delete.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/show.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
Labels: auto-merge, hacktoberfest-accepted

#3621 chore(rust): hide node default value for node start/stop within help
  implementations/rust/ockam/ockam_command/src/node/start.rs
  implementations/rust/ockam/ockam_command/src/node/stop.rs
Labels: auto-merge, hacktoberfest-accepted

#3624 refactor(rust): use rpc abstraction with `tcp listener list` command
  implementations/rust/ockam/ockam_command/src/tcp/listener/list.rs
Labels: auto-merge, hacktoberfest-accepted

#3629 update mergify rule
  .github/mergify.yml
Labels: auto-merge

#3627 fix(rust): generalize `extract_node_name` so it can correctly parse other protocols
  implementations/rust/ockam/ockam_command/src/configuration/set_default_node.rs
  implementations/rust/ockam/ockam_command/src/forwarder/create.rs
  implementations/rust/ockam/ockam_command/src/identity/show.rs
  implementations/rust/ockam/ockam_command/src/message/send.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/create.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/delete.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/show.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
Labels: auto-merge

#3630 chore: move `cargo release` config file to `tools/scripts/release`
  tools/scripts/release/crate-bump.sh
  tools/scripts/release/crate-publish.sh
  tools/scripts/release/release.toml
Labels: auto-merge, hacktoberfest-accepted

#3634 refactor(rust): change `tcp outlet create` to use `rpc` abstraction
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/mod.rs
Labels: auto-merge

#3632 refactor(rust): refactor `tcp listener delete` command to use rpc abstraction
  implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
Labels: auto-merge, hacktoberfest-accepted

#3583 ci: lint cargo.lock in CI
  .github/workflows/lint-cargo.yml
Labels: auto-merge, hacktoberfest-accepted

#3622 chore(rust): ockam_command: unify help
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/admin/mod.rs
  implementations/rust/ockam/ockam_command/src/admin/subscription.rs
  implementations/rust/ockam/ockam_command/src/authenticated.rs
  implementations/rust/ockam/ockam_command/src/completion/mod.rs
  implementations/rust/ockam/ockam_command/src/configuration/mod.rs
  implementations/rust/ockam/ockam_command/src/credential/mod.rs
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/forwarder/create.rs
  implementations/rust/ockam/ockam_command/src/forwarder/mod.rs
  implementations/rust/ockam/ockam_command/src/help.rs
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/message/mod.rs
  implementations/rust/ockam/ockam_command/src/message/send.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/delete.rs
  implementations/rust/ockam/ockam_command/src/node/list.rs
  implementations/rust/ockam/ockam_command/src/node/mod.rs
  implementations/rust/ockam/ockam_command/src/node/run.rs
  implementations/rust/ockam/ockam_command/src/node/show.rs
  implementations/rust/ockam/ockam_command/src/node/start.rs
  implementations/rust/ockam/ockam_command/src/node/stop.rs
  implementations/rust/ockam/ockam_command/src/reset.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/create.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/delete.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/list.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/list.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/mod.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/mod.rs
  implementations/rust/ockam/ockam_command/src/secure_channel/show.rs
  implementations/rust/ockam/ockam_command/src/subscription.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
Labels: auto-merge

#3611 feat(rust): Validate project/space name for create command
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/project/create.rs
  implementations/rust/ockam/ockam_command/src/space/create.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
Labels: auto-merge, hacktoberfest-accepted

#3652 chore(elixir): remove unused implementation for sessions as separate workers
  implementations/elixir/ockam/ockam/lib/ockam/session/handshake.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/separate.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/separate/initiator.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/separate/pre_worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/separate/responder.ex
Labels: auto-merge

#3651 ci: change deprecated workflow set-output command to new syntax
  .github/workflows/documentation.yml
Labels: auto-merge

#3655 chore(typescript): remove wasm and napi prototypes
  implementations/typescript/ockam/ockam_nodejs_native/.npmignore
  implementations/typescript/ockam/ockam_nodejs_native/Cargo.lock
  implementations/typescript/ockam/ockam_nodejs_native/Cargo.toml
  implementations/typescript/ockam/ockam_nodejs_native/build.rs
  implementations/typescript/ockam/ockam_nodejs_native/index.d.ts
  implementations/typescript/ockam/ockam_nodejs_native/index.js
  implementations/typescript/ockam/ockam_nodejs_native/npm/darwin-arm64/README.md
  implementations/typescript/ockam/ockam_nodejs_native/npm/darwin-arm64/package.json
  implementations/typescript/ockam/ockam_nodejs_native/npm/darwin-x64/README.md
  implementations/typescript/ockam/ockam_nodejs_native/npm/darwin-x64/package.json
  implementations/typescript/ockam/ockam_nodejs_native/npm/linux-x64-gnu/README.md
  implementations/typescript/ockam/ockam_nodejs_native/npm/linux-x64-gnu/package.json
  implementations/typescript/ockam/ockam_nodejs_native/package.json
  implementations/typescript/ockam/ockam_nodejs_native/src/lib.rs
  implementations/typescript/ockam/ockam_wasm/package.json
  implementations/typescript/ockam/ockam_wasm/rust/Cargo.lock
  implementations/typescript/ockam/ockam_wasm/rust/Cargo.toml
  implementations/typescript/ockam/ockam_wasm/rust/README.md
  implementations/typescript/ockam/ockam_wasm/rust/src/lib.rs
  implementations/typescript/ockam/ockam_wasm/rust/src/utils.rs
  implementations/typescript/ockam/ockam_wasm/rust/tests/web.rs
  implementations/typescript/ockam/ockam_wasm/src/index.ts
  implementations/typescript/ockam/ockam_wasm/tsconfig.json
  implementations/typescript/yarn.lock
Labels: auto-merge

#3636 feat(rust): project delete should work with projects that fail to start
  implementations/rust/ockam/ockam_api/src/config/lookup.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_command/src/project/create.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
  implementations/rust/ockam/ockam_command/src/util/config.rs
Labels: auto-merge, hacktoberfest-accepted

#3607 refactor(rust): `node create` to return result
  Cargo.lock
  implementations/rust/ockam/ockam_command/src/error.rs
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
Labels: auto-merge

#3659 fix(rust): project info was not persisted properly
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
Labels: auto-merge

#3656 fix(rust): fix service start from launch config file
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/service/start.rs
Labels: auto-merge

#3658 ci: replace deprecated set-output command with GitHub output parameter
  .github/workflows/create-release-pull-request.yml
Labels: auto-merge

#3660 ci: change deprecated workflow set-output command to new syntax
  .github/workflows/release-binaries.yml
Labels: auto-merge, hacktoberfest-accepted

#3610 refactor(rust): `node start` reads from the config file to execute the `on_node_startup` commands
  implementations/rust/ockam/ockam_api/src/config/cli.rs
  implementations/rust/ockam/ockam_api/src/config/mod.rs
  implementations/rust/ockam/ockam_api/src/nodes/config.rs
  implementations/rust/ockam/ockam_api/src/nodes/mod.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/identity.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/vault.rs
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/list.rs
  implementations/rust/ockam/ockam_command/src/node/show.rs
  implementations/rust/ockam/ockam_command/src/node/start.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
  implementations/rust/ockam/ockam_command/src/space/util.rs
  implementations/rust/ockam/ockam_command/src/util/config.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
  implementations/rust/ockam/ockam_command/src/util/startup.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3662 refactor(rust): stop mapping errors manually in configuration set
  implementations/rust/ockam/ockam_command/src/configuration/set.rs
Labels: auto-merge

#3667 ci: replace deprecated set-output command with output parameter in Co…
  .github/workflows/ockam-package.yml
Labels: auto-merge

#3668 refactor(rust): refactored identity show command to use rpc abstraction
  implementations/rust/ockam/ockam_api/src/nodes/models/identity.rs
  implementations/rust/ockam/ockam_command/src/identity/mod.rs
  implementations/rust/ockam/ockam_command/src/identity/show.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge, hacktoberfest-accepted

#3657 feat(rust): add addons commands
  implementations/rust/ockam/ockam_api/src/cloud/addon.rs
  implementations/rust/ockam/ockam_api/src/cloud/mod.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/project/mod.rs
  implementations/rust/ockam/ockam_command/src/subscription.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3674 fix(rust): keep project id as string
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/util.rs
Labels: auto-merge

#3669 refactor(rust): use rpc abstraction for secure-channel listener create
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs
Labels: auto-merge, hacktoberfest-accepted

#3679 chore(rust): allow to store custom attributes for issuing credentials
  implementations/rust/ockam/ockam_api/src/authenticator/direct.rs
  implementations/rust/ockam/ockam_api/tests/auth.rs
Labels: auto-merge

#3673 feat(rust): add okta auth command
  implementations/rust/ockam/ockam_api/src/cloud/addon.rs
  implementations/rust/ockam/ockam_api/src/cloud/enroll.rs
  implementations/rust/ockam/ockam_api/src/cloud/project.rs
  implementations/rust/ockam/ockam_api/src/config/lookup.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/project/auth.rs
  implementations/rust/ockam/ockam_command/src/project/info.rs
  implementations/rust/ockam/ockam_command/src/project/mod.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
Labels: auto-merge

#3672 feat(rust): okta identity provider
  Cargo.lock
  implementations/rust/ockam/ockam_api/Cargo.toml
  implementations/rust/ockam/ockam_api/src/cloud/enroll.rs
  implementations/rust/ockam/ockam_api/src/cloud/project.rs
  implementations/rust/ockam/ockam_api/src/lib.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/services.rs
  implementations/rust/ockam/ockam_api/src/nodes/registry.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/services.rs
  implementations/rust/ockam/ockam_api/src/okta/mod.rs
  implementations/rust/ockam/ockam_command/src/enroll.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/project/auth.rs
  implementations/rust/ockam/ockam_command/src/project/enroll.rs
  implementations/rust/ockam/ockam_command/src/project/util.rs
  implementations/rust/ockam/ockam_command/src/service/config.rs
  implementations/rust/ockam/ockam_command/src/service/start.rs
Labels: auto-merge

#3680 refactor(rust): refactored node show command
  implementations/rust/ockam/ockam_command/src/node/show.rs
Labels: auto-merge, hacktoberfest-accepted

#3697 refactor(bash): Remove shebang multiple parameter in script
  tools/scripts/release/changelog.sh
  tools/scripts/release/crate-bump.sh
  tools/scripts/release/crate-publish.sh
  tools/scripts/release/crates-to-publish.sh
Labels: auto-merge

#3704 feat(rust): support node config upgrades
  implementations/rust/ockam/ockam_api/src/config/cli.rs
  implementations/rust/ockam/ockam_api/src/config/mod.rs
  implementations/rust/ockam/ockam_api/src/nodes/config.rs
  implementations/rust/ockam/ockam_command/src/util/config.rs
Labels: auto-merge

#3708 make downloading latest release a 1 liner
  install.sh
Labels: auto-merge, hacktoberfest-accepted

#3714 build(rust): Move cross config
  Cargo.toml
  Cross.Dockerfile.aarch64
  Cross.Dockerfile.armv7
  Cross.toml
  tools/cross/Cross.Dockerfile.aarch64
  tools/cross/Cross.Dockerfile.armv7
Labels: auto-merge, hacktoberfest-accepted

#3713 ci: pin `import_gpg` action to hash
  .github/workflows/create-release-pull-request.yml
  .github/workflows/release-binaries.yml
Labels: auto-merge, hacktoberfest-accepted

#3719 Prepare #3705
  .devcontainer/Dockerfile
  .github/actions/cargo_home_cache/action.yml
  .github/actions/cargo_target_dir_cache/action.yml
  .github/actions/elixir_cache/action.yml
  .github/actions/gradle_cache/action.yml
  .github/workflows/all.yml
  .github/workflows/documentation.yml
  .github/workflows/elixir.yml
  .github/workflows/lint-cargo.yml
  .github/workflows/rust.yml
  examples/rust/ockam_kafka/Dockerfile
  examples/rust/tcp_inlet_and_outlet/Dockerfile
  integrations/suborbital/demo/Dockerfile
Labels: auto-merge

#3706 chore: avoid including nulls in json output on optional fields
  implementations/rust/ockam/ockam_api/src/cloud/project.rs
  implementations/rust/ockam/ockam_command/src/project/info.rs
Labels: auto-merge

#3695 feat(rust): add policy command
  Cargo.lock
  implementations/rust/ockam/ockam_abac/Cargo.toml
  implementations/rust/ockam/ockam_abac/src/eval.rs
  implementations/rust/ockam/ockam_abac/src/expr.rs
  implementations/rust/ockam/ockam_abac/src/mem.rs
  implementations/rust/ockam/ockam_abac/src/traits.rs
  implementations/rust/ockam/ockam_abac/src/types.rs
  implementations/rust/ockam/ockam_api/src/lib.rs
  implementations/rust/ockam/ockam_api/src/lmdb.rs
  implementations/rust/ockam/ockam_api/src/nodes/config.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/mod.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/policy.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/policy.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/lib.rs
  implementations/rust/ockam/ockam_command/src/policy.rs
  implementations/rust/ockam/ockam_core/src/api.rs
Labels: auto-merge

#3724 chore(rust): do not run the addon tests on CI
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3727 feat(rust): add command to list policies of a resource
  implementations/rust/ockam/ockam_abac/src/mem.rs
  implementations/rust/ockam/ockam_abac/src/traits.rs
  implementations/rust/ockam/ockam_api/src/lmdb.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/policy.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/policy.rs
  implementations/rust/ockam/ockam_command/src/policy.rs
Labels: auto-merge

#3723 Avoid recursion when processing policy expressions.
  Cargo.lock
  implementations/rust/ockam/ockam_abac/Cargo.toml
  implementations/rust/ockam/ockam_abac/src/eval.rs
  implementations/rust/ockam/ockam_abac/src/expr.rs
  implementations/rust/ockam/ockam_abac/src/parser.rs
  implementations/rust/ockam/ockam_core/src/compat.rs
Labels: auto-merge

#3725 chore(rust): pretty print credentials
  implementations/rust/ockam/ockam_command/src/project/auth.rs
  implementations/rust/ockam/ockam_identity/src/credential.rs
Labels: auto-merge

#3720 refactor(rust): `tcp connection create` use `rpc` abstraction
  implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge, hacktoberfest-accepted

#3738 feat(rust): copy custom attributes from okta profiles into credentials
  implementations/rust/ockam/ockam_api/src/authenticator/direct.rs
  implementations/rust/ockam/ockam_api/src/cloud/project.rs
  implementations/rust/ockam/ockam_api/src/nodes/models/services.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/services.rs
  implementations/rust/ockam/ockam_api/src/okta/mod.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/service/config.rs
  implementations/rust/ockam/ockam_command/src/service/start.rs
Labels: auto-merge

#3726 Resolves #3722: Format all bash scripts using shfmt
  implementations/elixir/ockam/ockam_vault_software/build-elixir-universal-lib.sh
  install.sh
  tools/docs/check_documentation.sh
  tools/scripts/release/acceptance_tests.sh
  tools/scripts/release/changelog.sh
  tools/scripts/release/crate-bump.sh
  tools/scripts/release/crate-publish.sh
  tools/scripts/release/crates-to-publish.sh
  tools/scripts/release/delete_draft.sh
  tools/scripts/release/publish-order.sh
  tools/scripts/release/release.sh
Labels: auto-merge

#3743 refactor(rust): add support to `project enroll` to set attributes
  implementations/rust/ockam/ockam_api/src/authenticator/direct.rs
  implementations/rust/ockam/ockam_api/src/authenticator/direct/types.rs
  implementations/rust/ockam/ockam_api/tests/auth.rs
  implementations/rust/ockam/ockam_command/src/project/addon.rs
  implementations/rust/ockam/ockam_command/src/project/enroll.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3751 prepare 3734
  implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/inlet/mod.rs
Labels: auto-merge

#3752 Prepare #3689
  .github/workflows/shellcheck.yml
Labels: auto-merge

#3699 Noyez vis change hist identity show
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/identity/show.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
  implementations/rust/ockam/ockam_core/src/vault/types.rs
  implementations/rust/ockam/ockam_identity/src/change.rs
  implementations/rust/ockam/ockam_identity/src/change/create_key.rs
  implementations/rust/ockam/ockam_identity/src/change/rotate_key.rs
  implementations/rust/ockam/ockam_identity/src/change_history.rs
  implementations/rust/ockam/ockam_identity/src/identifiers.rs
  implementations/rust/ockam/ockam_identity/src/key_attributes.rs
  implementations/rust/ockam/ockam_identity/src/signature.rs
Labels: auto-merge, hacktoberfest-accepted

#3744 feat(rust): Reduce output for short help command
  implementations/rust/ockam/ockam_command/src/lib.rs
Labels: auto-merge, hacktoberfest-accepted

#3746 fix(rust): Show help output when no args passed
  implementations/rust/ockam/ockam_command/src/subscription.rs
Labels: auto-merge, hacktoberfest-accepted

#3757 fix(rust): auth0 error message text when failing to validate provider config
  implementations/rust/ockam/ockam_command/src/enroll.rs
Labels: auto-merge

#3735 feat(rust): complete policy delete functionality
  implementations/rust/ockam/ockam_abac/src/parser.rs
  implementations/rust/ockam/ockam_api/src/lmdb.rs
  implementations/rust/ockam/ockam_api/src/nodes/service.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/policy.rs
  implementations/rust/ockam/ockam_command/src/policy.rs
Labels: auto-merge

#3750 fix(elixir): take service worker id from address if address is configured
  implementations/elixir/ockam/ockam_services/lib/services/provider.ex
Labels: auto-merge

#3716 feat(rust): add option to create vaults without nodes
  implementations/rust/ockam/ockam_command/src/vault/create.rs
Labels: auto-merge, hacktoberfest-accepted

#3747 fix(rust): type untyped rpc::parse_response() calls
  implementations/rust/ockam/ockam_command/src/identity/create.rs
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge, hacktoberfest-accepted

#3736 feat(rust): print rustc version in workflows
  .github/workflows/ockam_command.yml
  .github/workflows/rust.yml
Labels: auto-merge

#3755 refactor(rust): restrict info shown on output of enroll command
  implementations/rust/ockam/ockam_command/src/util/output.rs
Labels: auto-merge, hacktoberfest-accepted

#3765 test: add more test for `vault create` command
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge, hacktoberfest-accepted

#3764 refactor(rust): show help when no args passed on `vault create` command
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/tests/commands.bats
Labels: auto-merge

#3766 ci: fix shellcheck errors in release.sh
  tools/scripts/release/release.sh
Labels: auto-merge

#3756 ci: fix shellcheck errors in acceptance_tests.sh
  tools/scripts/release/acceptance_tests.sh
Labels: auto-merge, hacktoberfest-accepted

#3771 Prepare #3715
  tools/docker/builder/Dockerfile
Labels: auto-merge

#3698 ci: add shfmt workflow
  .github/workflows/shfmt.yml
Labels: auto-merge, hacktoberfest-accepted

#3762 Added `arg_required_else_help = true` to `tcp connection` commands
  implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/connection/mod.rs
Labels: auto-merge, hacktoberfest-accepted

#3772 Refactor tcp listener create command to use rpc abstraction and to stop mapping errors manually
  implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
Labels: auto-merge, hacktoberfest-accepted

#3759 refactor(rust): reduce repeated logic, make use of `rpc`
  implementations/rust/ockam/ockam_api/src/nodes/models/portal.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs
  implementations/rust/ockam/ockam_command/src/node/create.rs
  implementations/rust/ockam/ockam_command/src/node/list.rs
  implementations/rust/ockam/ockam_command/src/node/show.rs
  implementations/rust/ockam/ockam_command/src/node/start.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
Labels: auto-merge, hacktoberfest-accepted

#3767 fix(elixir): improve error message on abac policy check
  implementations/elixir/ockam/ockam_abac/lib/policy_check.ex
  implementations/elixir/ockam/ockam_services/test/services/abac_policies_api_test.exs
Labels: auto-merge
