Repository build-trust/ockam, pull requests merged in 2023-11, with the labels that each got.

#6807 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6681 Replaced the rust doc command
  implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6808 fixes#6143 changed the message in project list
  implementations/rust/ockam/ockam_command/src/project/list.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6810 feat(rust): add `plain` and `json` outputs to `ockam node logs` (issu…
  implementations/rust/ockam/ockam_command/src/node/logs.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6749 feat(rust): interactive ockam node start
  implementations/rust/ockam/ockam_command/src/node/start.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6748 fix(rust):replaced termimad with formatdoc & opts.terminal.stdout() in authenticated
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/authenticated.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6816 Adding myself to the CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6817 adding myself to CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6832 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: CLA-ACCEPTANCE

#6811 fix typos and grammatical mistake in README.md file
  README.md
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6874 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: CLA-ACCEPTANCE
