Repository build-trust/ockam, pull requests merged in 2023-10, with the labels that each got.

#6205 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, CLA-ACCEPTANCE

#6209 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, CLA-ACCEPTANCE

#6211 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, CLA-ACCEPTANCE

#6196 changed status error messages
  implementations/rust/ockam/ockam_command/src/status.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6184 feat(rust): Add JSON output support for `vault list` and `vault show`
  implementations/rust/ockam/ockam_api/src/cli_state/vaults.rs
  implementations/rust/ockam/ockam_command/src/vault/list.rs
  implementations/rust/ockam/ockam_command/src/vault/show.rs
  implementations/rust/ockam/ockam_command/tests/bats/vault.bats
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6213 docs(rust): improve docs for `ockam enroll` and `ockam identity show`
  implementations/rust/ockam/ockam_command/src/enroll/static/long_about.txt
  implementations/rust/ockam/ockam_command/src/identity/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6197 improve enroll help message
  implementations/rust/ockam/ockam_command/src/lib.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6252 cla: accepted by `petersooley`
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6267 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6242 docs(rust): improve feedback section of the help text
  implementations/rust/ockam/ockam_command/src/docs.rs
  implementations/rust/ockam/ockam_command/src/identity/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6256 fix(rust): improve ockam space list when there are no spaces
  implementations/rust/ockam/ockam_command/src/space/list.rs
  implementations/rust/ockam/ockam_command/src/terminal/mod.rs
Labels: hacktoberfest

#6271 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: hacktoberfest, CLA-ACCEPTANCE

#6280 fix(elixir): fix examples
  examples/elixir/get_started/04-routing-over-transport-responder.exs
  examples/elixir/get_started/05-routing-over-transport-two-hops-middle.exs
  examples/elixir/get_started/05-routing-over-transport-two-hops-responder.exs
Labels: HACKTOBERFEST-ACCEPTED

#6272 cla: add mickm3n
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6273 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6274 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6278 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6282 cla: add dogpawhat
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6288 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6301 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6307 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6308 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6276 Updated identity argument value name and added Doc string(Fixes #6248)
  implementations/rust/ockam/ockam_command/src/credential/get.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6268 docs(rust): update value_name on issuer arg in credential store
  implementations/rust/ockam/ockam_command/src/credential/store.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6269 refactor(rust): remove path arguement from vault create cmd
  implementations/rust/ockam/ockam_command/src/vault/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6313 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6215 docs(rust): improve cli "learn more" section from the help text
  implementations/rust/ockam/ockam_command/src/docs.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6244 feat(rust): Improve JSON output of ockam node show
  implementations/rust/ockam/ockam_command/src/node/mod.rs
  implementations/rust/ockam/ockam_command/src/node/models/mod.rs
  implementations/rust/ockam/ockam_command/src/node/models/portal.rs
  implementations/rust/ockam/ockam_command/src/node/models/secure_channel.rs
  implementations/rust/ockam/ockam_command/src/node/models/services.rs
  implementations/rust/ockam/ockam_command/src/node/models/show.rs
  implementations/rust/ockam/ockam_command/src/node/models/transport.rs
  implementations/rust/ockam/ockam_command/src/node/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6260 #6251 renamed identity to identity_name
  implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6277 Update Identity argument name & doc string for authority (issue #6245)
  implementations/rust/ockam/ockam_command/src/authority/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6330 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6217 refactor(elixir): replaces deprecated Logger.warn
  implementations/elixir/ockam/ockam/lib/ockam/messaging/delivery/resend_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/monotonic/index_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/strict/confirm_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/strict/index_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/node.ex
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/portal/interceptor.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/portal/outlet_worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/handler.ex
  implementations/elixir/ockam/ockam/lib/ockam/worker.ex
  implementations/elixir/ockam/ockam_abac/lib/authorization.ex
  implementations/elixir/ockam/ockam_healthcheck/lib/healthcheck/healthcheck.ex
  implementations/elixir/ockam/ockam_kafka/lib/interceptor/kafka_interceptor.ex
  implementations/elixir/ockam/ockam_services/lib/services/metrics/telemetry_poller.ex
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6331 accepted cla
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6355 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6361 cla: accepted by `racnan`
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6279 Updated identity argument value name and added doc string(Fixes #6247)
  implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6195 feat(rust): improve output for 'ockam identity default'
  implementations/rust/ockam/ockam_command/src/identity/default.rs
  implementations/rust/ockam/ockam_command/tests/bats/identity.bats
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6309 docs(rust): improve documentation for `ockam relay` command
  implementations/rust/ockam/ockam_command/src/relay/static/long_about.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6398 cla: accepted by `axd99`
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6401 cla: accepted by Asymtode712
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6410 cla: accepted by dhruvmehtaaa
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6412 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6421 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6427 docs(rust): update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6409 updated ockam tcp-outlet help text (fixes #6339)
  implementations/rust/ockam/ockam_command/src/tcp/outlet/static/long_about.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6400 docs(rust): Improve ockam enroll argument --identity (clap command)
  implementations/rust/ockam/ockam_command/src/enroll/command.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6407 updated identity value name and added doc string (fixes #6246)
  implementations/rust/ockam/ockam_command/src/node/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6357 docs(rust): update `ockam tcp-outlet --help` documentation & `--at` argument help message
  implementations/rust/ockam/ockam_command/src/node/mod.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6420 fix(ockam/node): Rename vault argument to VAULT_NAME and add doc string
  implementations/rust/ockam/ockam_command/src/node/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6371 fix(rust): improve ockam tcp-outlet delete --help text
  implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6428 docs: remove duplicated (and outdated) type of shells from `ockam completion` command
  implementations/rust/ockam/ockam_command/src/completion/mod.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6356 Improve ockam relay list --help documentation
  implementations/rust/ockam/ockam_command/src/relay/list.rs
  implementations/rust/ockam/ockam_command/src/relay/static/list/after_long_help.txt
  implementations/rust/ockam/ockam_command/src/relay/static/list/long_about.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6418 fix(ockam/credential): set the vault argument value name on ockam credential issue
  implementations/rust/ockam/ockam_command/src/credential/issue.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6327 fix(rust): fix create relay return when not enrolled
  implementations/rust/ockam/ockam_command/src/relay/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6369 docs(rust): Improve ockam tcp-inlet --help text
  implementations/rust/ockam/ockam_command/src/tcp/inlet/static/long_about.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6416 Changed vault argument name to VAULT_NAME
  implementations/rust/ockam/ockam_command/src/credential/list.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6436 feat(rust): Add JSON output to ockam identity list
  implementations/rust/ockam/ockam_command/src/identity/list.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6328 refactor(rust): improve ockam enroll project config step by warning u…
  implementations/rust/ockam/ockam_command/src/operation/util.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6408 Changed vault argument value name to VAULT_NAME
  implementations/rust/ockam/ockam_command/src/authority/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6437 fix(rust): Add the --identity flag to the ockam space create command...
  implementations/rust/ockam/ockam_command/src/space/create.rs
  implementations/rust/ockam/ockam_command/src/util/api.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6358 docs(rust): update `ockam relay create --help` message (#6294)
  implementations/rust/ockam/ockam_command/src/relay/create.rs
  implementations/rust/ockam/ockam_command/src/relay/static/create/long_about.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6439 cla:accepted by utkarsh1042005
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6441 chore: update CONTRIBUTORS.csv to sign CLA
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6443 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6372 fixes#6056 adding troubleshoot
  implementations/rust/ockam/ockam_command/src/enroll/static/after_long_help.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6397 Renamed the vault parameter to vault_name In CreateSecureChannelListenerRequest
  implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs
  implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6392 Used the random_name function in vault create
  implementations/rust/ockam/ockam_command/src/vault/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6394 Used the random_name function in node create command
  implementations/rust/ockam/ockam_command/src/node/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6348 feat(rust): Improve ockam identity show with json
  implementations/rust/ockam/ockam_command/src/identity/show.rs
  implementations/rust/ockam/ockam_command/src/output/output.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6367 feat(rust): support json output for tcp-outlet list
  implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6396 Used the random_name function in identity create command
  implementations/rust/ockam/ockam_command/src/identity/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6411 Use the random_name function on the space_name argument of the space …
  implementations/rust/ockam/ockam_command/src/space/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6349 feat(rust): support json output for tcp-outlet show
  implementations/rust/ockam/ockam_command/src/tcp/outlet/show.rs
  implementations/rust/ockam/ockam_command/tests/bats/portals.bats
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6413 chore(rust): changed the argument to random_name() .
  implementations/rust/ockam/ockam_command/src/project/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6458 CLA acceptance
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6470 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6479 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6451 Updated vault argument value to VAULT_NAME (Fixes #6390)
  implementations/rust/ockam/ockam_command/src/credential/verify.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6395 Used the random_name function in the Default implementation of NodeManagerDefaults
  implementations/rust/ockam/ockam_api/src/nodes/service/in_memory_node.rs
Labels: hacktoberfest

#6503 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6507 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6513 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6506 fix(rust): increase timeout of rust test
  implementations/rust/ockam/ockam_api/src/kafka/integration_test.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6526 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6530 Accepted cla
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6533 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6534 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6535 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6537 chore: Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: hacktoberfest, CLA-ACCEPTANCE

#6495 fix(rust): Abort on ockam enroll --output json
  implementations/rust/ockam/ockam_command/src/enroll/command.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6540 Accept and sign CLA
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6449 feat(rust): improve `ockam vault list` to mark the default vault
  implementations/rust/ockam/ockam_api/src/cli_state/vaults.rs
  implementations/rust/ockam/ockam_command/src/output/output.rs
  implementations/rust/ockam/ockam_command/src/vault/list.rs
  implementations/rust/ockam/ockam_command/tests/bats/vault.bats
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6498 [Fix]: node delete command
  implementations/rust/ockam/ockam_command/src/node/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6499 [Fix]: trust-context default command
  implementations/rust/ockam/ockam_command/src/trust_context/default.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6500 vault-create-command
  implementations/rust/ockam/ockam_command/src/vault/create.rs
  implementations/rust/ockam/ockam_command/src/vault/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6493 [Fix]: space delete command
  implementations/rust/ockam/ockam_command/src/space/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6501 [Fix]: tcp-inlet delet command
  implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6516 [Fix]: Use ```Terminal``` to print output instead of ```println``` in the ```project show``` command
  implementations/rust/ockam/ockam_command/src/project/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6517 [Fix]: Use ```Terminal``` to print output instead of ```println``` in the ```space show``` command
  implementations/rust/ockam/ockam_command/src/space/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6518 [Fix]: Use ```Terminal``` to print output instead of ```println``` in the ```secure-channel show``` command
  implementations/rust/ockam/ockam_command/src/secure_channel/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6542 refactor(rust): Use terminal for tcp-listener show
  implementations/rust/ockam/ockam_command/src/tcp/listener/show.rs
Labels: hacktoberfest

#6541 Improve relay `--help` example
  implementations/rust/ockam/ockam_command/src/relay/static/after_long_help.txt
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6529 [Fix]: Flatten json output for ```identity list``` command
  implementations/rust/ockam/ockam_command/src/identity/list.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6546 cla:accepted by utkarsh1042005 CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6578 fix: flatten json output for trust-context delete
  implementations/rust/ockam/ockam_command/src/trust_context/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6612 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: hacktoberfest, CLA-ACCEPTANCE

#6586 CI - rename `nix_installer_and_cache` to `cache_nix` in make workflow
  .github/workflows/make.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6585 ci: rename elixir_cache to cache_elixir in elixir workflow
  .github/workflows/elixir.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6445 fix(rust): handle error returned by node
  examples/rust/file_transfer/examples/sender.rs
  implementations/rust/ockam/ockam/tests/node/std/pass_with_imported_context.rs
  implementations/rust/ockam/ockam/tests/node/std/pass_with_more_than_one_arg.rs
  implementations/rust/ockam/ockam/tests/node/std/pass_with_non_async_fn.rs
  implementations/rust/ockam/ockam/tests/node/std/pass_with_ockam_alias.rs
  implementations/rust/ockam/ockam_command/src/util/mod.rs
  implementations/rust/ockam/ockam_node/src/executor.rs
  implementations/rust/ockam/ockam_transport_ble/examples/04-routing-over-ble-transport-initiator.rs
  implementations/rust/ockam/ockam_transport_ble/examples/05-secure-channel-over-ble-transport-initiator.rs
Labels: hacktoberfest

#6617 fix: change to rust local action
  .github/workflows/rust.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6536 ci: split elixir cache to save and restore cache
  .github/actions/elixir_cache/action.yml
Labels: hacktoberfest

#6480 delete node interactively
  Cargo.lock
  implementations/rust/ockam/ockam_command/Cargo.toml
  implementations/rust/ockam/ockam_command/src/node/delete.rs
  implementations/rust/ockam/ockam_command/src/terminal/mod.rs
  implementations/rust/ockam/ockam_command/src/terminal/tui.rs
Labels: hacktoberfest

#6582 Rename nix_installer_and_cache to cache_nix
  .github/workflows/elixir.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6618 renamed nix_installer_and_cache to cache_nix
  .github/workflows/rust.yml
Labels: hacktoberfest

#6630 chore(ci): use rust local action for `test_ockam_command` job
  .github/workflows/rust.yml
Labels: hacktoberfest

#6616 CLA: Accepted by nabeel001 CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6620 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6635 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6584 Fix: Flatten json output for the `project create` command
  implementations/rust/ockam/ockam_command/src/project/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6590 feat(rust): flatten json output for project delete command
  implementations/rust/ockam/ockam_command/src/project/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6599 feat(rust): Flatten json output for `identity create` command
  implementations/rust/ockam/ockam_command/src/identity/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6602 feat(rust): Flatten json output for `tcp-outlet delete` command
  implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6601 feat(rust): Flatten json output for `tcp-listener delete` command
  implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6607 [Fix]: flatten json output for ```policy delete``` command
  implementations/rust/ockam/ockam_command/src/policy/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6600 [Fix]: ```relay``` is deleted
  implementations/rust/ockam/ockam_command/src/relay/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6604 [Fix]:Changed ```println``` to ```terminal```
  implementations/rust/ockam/ockam_command/src/credential/show.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6606 [Fix]: use ```Terminal``` to print output instead of ```println``` in the ```space create``` command
  implementations/rust/ockam/ockam_command/src/space/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6605 Updated vault argument value to VAULT_NAME (Fixes #6389)
  implementations/rust/ockam/ockam_command/src/credential/store.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6609 default node is displayed instead of error
  implementations/rust/ockam/ockam_command/src/node/default.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6638 fix: use rust local action in make.yml
  .github/workflows/make.yml
Labels: hacktoberfest

#6636 ci: use local cache action for rust lint job
  .github/workflows/rust.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6637 fix: use rust local action for caching of dependencies in rust test_doc
  .github/workflows/rust.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6642 refactor(rust): flatten default vault
  implementations/rust/ockam/ockam_command/src/vault/default.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6587 CI: split Nix cache as separate save and restore cache
  .github/actions/cache_nix/action.yml
  .github/actions/nix_installer_and_cache/action.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6633 fix: use rust local action for caching of dependencies in elixir test…
  .github/workflows/elixir.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6610 [Fix]: Flatten json output for ```tcp-connection delete``` command
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6611 [Fix]: Flatten json output for ```vault default``` command
  implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6632 `ockam-enroll`: improve command output when creating identity
  implementations/rust/ockam/ockam_command/src/identity/mod.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6664 renamed nix_installer_and_cache to cache_nix in shell workflow
  .github/workflows/shell.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6666 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6661 Improve ockam tcp-inlet delete --help text (clap command)
  implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs
  implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6667 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6669 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6697 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6724 Update CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6670 fix: rename elixir_cache to cache_elixir
  .github/workflows/make.yml
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#5701 refactor(elixir): route from router.route/1 to worker.router/2 #3654
  examples/elixir/get_started/echoer.exs
  examples/elixir/get_started/hop.exs
  implementations/elixir/README.md
  implementations/elixir/ockam/ockam/lib/ockam/examples/echoer.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/hop.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/messaging/shuffle.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/ping_pong.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/session/count_to/data_worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/examples/session/routing/data_worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/confirm_pipe/receiver.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/delivery/resend_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/index_pipe/sender.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/monotonic/index_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/strict/confirm_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/strict/index_pipe.ex
  implementations/elixir/ockam/ockam/lib/ockam/messaging/pipe_channel/simple.ex
  implementations/elixir/ockam/ockam/lib/ockam/secure_channel/channel.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/pluggable.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/pluggable/responder.ex
  implementations/elixir/ockam/ockam/lib/ockam/session/spawner.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional/publisher_proxy.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional/subscribe.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/client/consumer.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/client/publisher.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/index/service.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/workers/service.ex
  implementations/elixir/ockam/ockam/lib/ockam/stream/workers/stream.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/portal/inlet_worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/portal/interceptor.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/portal/outlet_worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/client.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/recoverable_client.ex
  implementations/elixir/ockam/ockam/lib/ockam/transport/udp/listener.ex
  implementations/elixir/ockam/ockam/lib/ockam/worker.ex
  implementations/elixir/ockam/ockam/lib/ockam/workers/pub_sub_subscriber.ex
  implementations/elixir/ockam/ockam/lib/ockam/workers/remote_forwarder.ex
  implementations/elixir/ockam/ockam/test/ockam/api/client_test.exs
  implementations/elixir/ockam/ockam/test/ockam/helpers/test_echoer.ex
  implementations/elixir/ockam/ockam/test/ockam/secure_channel_test.exs
  implementations/elixir/ockam/ockam_abac/test/helpers/echoer.ex
  implementations/elixir/ockam/ockam_kafka/test/interceptor/interceptor_test.exs
  implementations/elixir/ockam/ockam_services/lib/services/echo.ex
  implementations/elixir/ockam/ockam_services/lib/services/forwarding.ex
  implementations/elixir/ockam/ockam_services/lib/services/proxy.ex
  implementations/elixir/ockam/ockam_services/test/services/forwarding_test.exs
Labels: Implementation: Elixir, HACKTOBERFEST-ACCEPTED

#6729 Updated CONTRIBUTORS.csv
  .github/CONTRIBUTORS.csv
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest, CLA-ACCEPTANCE

#6640 Fix: tcp-listener create command using Terminal to output
  implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest

#6726 comments for AbortNode behaviour
  implementations/rust/ockam/ockam_node/src/executor.rs
  implementations/rust/ockam/ockam_node/src/router/mod.rs
  implementations/rust/ockam/ockam_node/src/router/shutdown.rs
Labels: hacktoberfest
